#!/usr/bin/env bash

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

active_pid=

main() {
  pushd "$ROOT" &> /dev/null
    binary=`ls ./cmd | head -n1`
    if [[ $? -eq 0 ]]; then
      compile_path="./cmd/${binary}"
    else
      binary=`basename "$ROOT"`
      compile_path="."
    fi
  popd &> /dev/null

  set -e

  version="unknown"
  if [[ -f .version ]]; then
    version=`cat .version`
  fi

  commit=`git rev-list -1 HEAD`
  dirty=
  if [[ ! -z "$(git status --untracked-files=no --porcelain)" ]]; then
    dirty="dirty"
  fi

  pushd "$ROOT" &> /dev/null
    go install -ldflags "-X main.Version=$version" "${compile_path}"
  popd &> /dev/null

  if [[ $KILL_AFTER != "" ]]; then
    "`go env GOPATH`/bin/${binary}" "$@" &
    active_pid=$!

    sleep $KILL_AFTER
    kill -s TERM $active_pid &> /dev/null || true
  else
    exec "`go env GOPATH`/bin/${binary}" "$@"
  fi
}

main "$@"

